### ISSUE TITLE
TickTock not works with R8 minifyEnabled true

### ISSUE THREAD

**Issue by VitaliyBelyaev** [ZacSweers/ticktock#38] opened 2020-10-15 16:55 UTC
Hi!

I faced with a problem when build my app with minifyEnabled true.
After analyzing apk I found that R8 delete all ticktock classes except `AndroidTzdbRulesInitializer`.

I found ticktock-runtime.pro in sources of ticktock-runtime, but rule that specified there seems to be not valid:
`-keep dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider`

There should be something like this:
`-keep class dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider { *; }`

I add that line to my proguard-rules.pro, but app crashes anyway.

It crashes on [that line ](https://github.com/ZacSweers/ticktock/blob/main/ticktock-runtime/src/main/java/dev/zacsweers/ticktock/runtime/TzdbZoneDataProvider.java#L142) with exception
`java.lang.NoSuchMethodException: j$.time.zone.ZoneRules.<init>`

I analyze intermediate `desugar_lib_dex` that L8 generates for desugaring classes and  `j$.time.zone.ZoneRules` present there and in `desugar_lib_project_keep_rules` rules there is line `-keep class j$.time.zone.ZoneRules`, but as I understand this will not keep all class members, it should be `-keep class j$.time.zone.ZoneRules { *; }`.

So it seems to be a bug in L8 mechanism  of minifying of desugaring classes.

I try to add `-keep class j$.time.zone.ZoneRules { *; }` to my proguard-rules.pro but there is no effect.
I try to add `-keep class java.time.zone.ZoneRules { *; }` to my proguard-rules.pro but there is also no effect.
I think there is because "L8 shrinks this dex file in isolation using the provided rules to produce the final, second dex file." as Jake Wharton pointed in his [article](https://jakewharton.com/d8-library-desugaring/).

Which workaround we can apply to make ticktock work with R8 minify?

**Comment by VitaliyBelyaev** [comment] 2020-10-15 16:57
Forgot to point TickTock version 0.1.1.

**Comment by VitaliyBelyaev** [comment] 2020-10-15 17:03
Android Gradle plugin version 4.0.1.

**Comment by VitaliyBelyaev** [comment] 2020-10-15 17:52
UPD
I try with `LazyZoneDataProvider` initialize in Application like this:
```
val provider = LazyZoneDataProvider.create(AssetsZoneDataLoader.create(this))
TickTockPlugins.setZoneDataProvider { provider }
```

No crash.

**Comment by VitaliyBelyaev** [comment] 2020-10-16 11:15
UPD
I make more research and found that `$j.time.zone.ZoneRules` is exists in second dex with all methods, so it seems to be that reflective call to find constructor [here](https://github.com/ZacSweers/ticktock/blob/main/ticktock-runtime/src/main/java/dev/zacsweers/ticktock/runtime/StandardZoneRules.java#L71) can't find constructor of ZoneRules:
```
     Caused by: java.lang.NoSuchMethodException: j$.time.zone.ZoneRules.<init> [class [J, class [Lj$.time.ZoneOffset;, class [J, class [Lj$.time.ZoneOffset;, class [Lj$.time.zone.ZoneOffsetTransitionRule;]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at h.b.a.b.e.a(:71)
        at h.b.a.b.d.d(:72) 
        at h.b.a.b.d.a(:66) 
        at h.b.a.b.h.f(:142) 
        at h.b.a.b.h.d(:103) 
        at h.b.a.b.h.e(:85) 
        at h.b.a.b.h.b(:50) 
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(:75) 
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312) 
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301) 
        at j$.time.zone.b.run(:154) 
        at java.security.AccessController.doPrivileged(AccessController.java:43) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.l.T(:120) 
        at j$.time.ZoneId.P(:412) 
        at j$.time.ZoneId.M(:360) 
        at j$.time.ZoneId.O(:316) 
        at j$.util.DesugarTimeZone.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
```
But I still don't understand why that happens.

**Comment by ZacSweers** [comment] 2020-10-30 18:17
Can you make a reproducible project? Are you using the androidx.startup?

**Comment by VitaliyBelyaev** [comment] 2020-11-02 12:48
Here [the branch in sample project](https://github.com/VitaliyBelyaev/tom-timer/tree/tick-tock-r8-example) to reproduce the crash.
Steps to reproduce:
1. `./gradlew clean assembleDebug`
2. Install apk through `adb install path/to/apk` or Device File Explorer
3. Launch the app


-  [This commit](https://github.com/VitaliyBelyaev/tom-timer/tree/51b52982d122d25def4e69e0d97c550c7fc19ae2) is a version of manual initialization without androidx.startup(I also try it with androidx.startup - same crash). Here I don't add any proguard rules for Tick Tock.

Here the full stacktrace:
```java
2020-11-02 15:08:43.282 21554-21554/ru.belyaev.vitaliy.tomtimer.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.belyaev.vitaliy.tomtimer.debug, PID: 21554
    java.lang.Error: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider
        at j$.time.r.e.run(:157)
        at java.security.AccessController.doPrivileged(AccessController.java:41)
        at j$.time.r.g.<clinit>(:145)
        at j$.time.r.g.b(:232)
        at j$.time.n.M(:120)
        at j$.time.ZoneId.I(:412)
        at j$.time.ZoneId.G(:360)
        at j$.time.ZoneId.H(:316)
        at j$.util.q.a(:190)
        at j$.time.ZoneId.systemDefault(:275)
        at j$.time.b.e(:178)
        at j$.time.LocalDateTime.now(:180)
        at ru.belyaev.vitaliy.tomtimer.AppActivity.i(:32)
        at ru.belyaev.vitaliy.tomtimer.AppActivity.onCreate(:27)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at j$.time.r.e.run(:152)
        at java.security.AccessController.doPrivileged(AccessController.java:41) 
        at j$.time.r.g.<clinit>(:145) 
        at j$.time.r.g.b(:232) 
        at j$.time.n.M(:120) 
        at j$.time.ZoneId.I(:412) 
        at j$.time.ZoneId.G(:360) 
        at j$.time.ZoneId.H(:316) 
        at j$.util.q.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
        at j$.time.b.e(:178) 
        at j$.time.LocalDateTime.now(:180) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.i(:32) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.onCreate(:27) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider" on path: DexPathList[[zip file "/data/app/ru.belyaev.vitaliy.tomtimer.debug-Po8Gp5rCcBq3vF6lkFQ--g==/base.apk"],nativeLibraryDirectories=[/data/app/ru.belyaev.vitaliy.tomtimer.debug-Po8Gp5rCcBq3vF6lkFQ--g==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at j$.time.r.e.run(:152) 
        at java.security.AccessController.doPrivileged(AccessController.java:41) 
        at j$.time.r.g.<clinit>(:145) 
        at j$.time.r.g.b(:232) 
        at j$.time.n.M(:120) 
        at j$.time.ZoneId.I(:412) 
        at j$.time.ZoneId.G(:360) 
        at j$.time.ZoneId.H(:316) 
        at j$.util.q.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
        at j$.time.b.e(:178) 
        at j$.time.LocalDateTime.now(:180) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.i(:32) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.onCreate(:27) 
        at android.app.Activity.performCreate(Activity.java:6975) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

- [This commit](https://github.com/VitaliyBelyaev/tom-timer/tree/89d68ff04e034b6f94483124f0878eafe334ca2e) is a version with proguard rule for `TickTockZoneRulesProvider` added. App crashes and stacktrace leads  to `Caused by: java.lang.NoSuchMethodException: j$.time.zone.ZoneRules.<init>` as I mentioned above.

Here the full stacktrace:
```java
2020-11-02 15:40:36.966 24533-24533/ru.belyaev.vitaliy.tomtimer.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.belyaev.vitaliy.tomtimer.debug, PID: 24533
    java.lang.Error: j$.time.zone.ZoneRulesException: Unable to load TZDB time-zone rules
        at j$.time.zone.a.run(:157)
        at java.security.AccessController.doPrivileged(AccessController.java:41)
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145)
        at j$.time.zone.ZoneRulesProvider.getRules(:232)
        at j$.time.m.M(:120)
        at j$.time.ZoneId.I(:412)
        at j$.time.ZoneId.G(:360)
        at j$.time.ZoneId.H(:316)
        at j$.util.q.a(:190)
        at j$.time.ZoneId.systemDefault(:275)
        at ru.belyaev.vitaliy.tomtimer.AppActivity.<init>(:14)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: j$.time.zone.ZoneRulesException: Unable to load TZDB time-zone rules
        at b.a.a.b.h.d(:105)
        at b.a.a.b.h.e(:85)
        at b.a.a.b.h.a(:50)
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(:75)
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312)
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301)
        at j$.time.zone.a.run(:154)
        at java.security.AccessController.doPrivileged(AccessController.java:41) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.m.M(:120) 
        at j$.time.ZoneId.I(:412) 
        at j$.time.ZoneId.G(:360) 
        at j$.time.ZoneId.H(:316) 
        at j$.util.q.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.<init>(:14) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.io.IOException: No constructor found
        at b.a.a.b.e.a(:80)
        at b.a.a.b.d.d(:72)
        at b.a.a.b.d.a(:66)
        at b.a.a.b.h.f(:142)
        at b.a.a.b.h.d(:103)
        at b.a.a.b.h.e(:85) 
        at b.a.a.b.h.a(:50) 
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(:75) 
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312) 
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301) 
        at j$.time.zone.a.run(:154) 
        at java.security.AccessController.doPrivileged(AccessController.java:41) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.m.M(:120) 
        at j$.time.ZoneId.I(:412) 
        at j$.time.ZoneId.G(:360) 
        at j$.time.ZoneId.H(:316) 
        at j$.util.q.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.<init>(:14) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.NoSuchMethodException: <init> [class [J, class [Lj$.time.ZoneOffset;, class [J, class [Lj$.time.ZoneOffset;, class [Lj$.time.zone.ZoneOffsetTransitionRule;]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at b.a.a.b.e.a(:71)
        at b.a.a.b.d.d(:72) 
        at b.a.a.b.d.a(:66) 
        at b.a.a.b.h.f(:142) 
        at b.a.a.b.h.d(:103) 
        at b.a.a.b.h.e(:85) 
        at b.a.a.b.h.a(:50) 
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(:75) 
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312) 
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301) 
        at j$.time.zone.a.run(:154) 
        at java.security.AccessController.doPrivileged(AccessController.java:41) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.m.M(:120) 
        at j$.time.ZoneId.I(:412) 
        at j$.time.ZoneId.G(:360) 
        at j$.time.ZoneId.H(:316) 
        at j$.util.q.a(:190) 
        at j$.time.ZoneId.systemDefault(:275) 
        at ru.belyaev.vitaliy.tomtimer.AppActivity.<init>(:14) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by VitaliyBelyaev** [comment] 2020-11-03 14:48
I found [an issue](https://issuetracker.google.com/issues/146362808) in Google Issue Tracker from which it is very clear that L8 using its own keep rules for desugared lib minification.

**Comment by VitaliyBelyaev** [comment] 2020-11-03 16:01
Create an [issue](https://issuetracker.google.com/u/2/issues/172325508) in Google Issue Tracker about R8 is minify private constructor of ZoneRules class that Tick Tock used in runtime through reflection.

**Comment by ZacSweers** [comment] 2020-12-27 02:45
This looks like an issue with our proguard rule due to wrong syntax, will fix

**Comment by ZacSweers** [comment] 2020-12-27 02:47
Actually I see you mentioned this in your PR description, leading to the rest. Let me re-read some more

**Comment by ZacSweers** [comment] 2020-12-27 02:51
@VitaliyBelyaev could you try this in your build? This would let you add arbitrary extra proguard configurations to the L8 task

```kotlin
tasks
    .named<L8DexDesugarLibTask>(androidTestL8Task)
    .configure {
       // Use one of these, either should work
       keepRulesFiles.from(<extra proguard rule files>)
       keepRulesConfigurations.set(listOf("-keep class j$.time.zone.ZoneRules { *; }"))
    }
}
```

**Comment by ZacSweers** [comment] 2020-12-27 02:52
Here is how we do similar patching in Keeper: https://github.com/slackhq/keeper/blob/main/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L131-L135

**Comment by VitaliyBelyaev** [comment] 2021-01-06 15:42
@ZacSweers I'm trying to apply workaround that you provided above, but it's not so simple. 

In Keeper you do this in plugin that do many other things like working with jars.

Could you please explain do I need create plugin too to apply that workaround or I can just create Gradle task that finds `L8DexDesugarLibTask` and configures it by adding my custom proguard rules for L8?

**Comment by ZacSweers** [comment] 2021-01-06 16:44
Yes the first code snippet I pasted

**Comment by kingsleyadio** [comment] 2021-03-01 14:53
Hi @ZacSweers 

I also ran into this problem while trying to use ticktock for our app
I noticed was that the proguard rules bundled with the library were not being merged with our app at all, so I had to manually copy them

Then [this](https://github.com/ZacSweers/ticktock/issues/38#issuecomment-709984303) one popped up. I used the solution you described [here](https://github.com/ZacSweers/ticktock/issues/38#issuecomment-751419005), but the issue only moved to another location. It seems it is all connected to [this issue](https://issuetracker.google.com/issues/179800061)

Do you think we may have a fix in the library that works on 4.x versions of AGP? Or do we have to wait altogether until it's possible to migrate to AGP 7.x?

Here's the new crash FYI
```
Caused by: java.lang.Error: j$.time.zone.ZoneRulesException: Unable to load TZDB time-zone rules
        at j$.time.zone.ZoneRulesProvider$a.run(:157)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145)
        at j$.time.zone.ZoneRulesProvider.getRules(:232)
        at j$.time.j.R(:120)
        at j$.time.ZoneId.N(:412)
        at j$.time.ZoneId.of(:360)
        at l84.f(SourceFile:313)
        at l84.O(SourceFile:101)
        at <omitted>(SourceFile:1102)
        at j4e.lb(SourceFile:344)
        at j4e.w6(SourceFile:332)
        at j4e.x6(Unknown Source:0)
        at m3e.accept(Unknown Source:4)
        at zaf.onSuccess(SourceFile:62)
        at iif$a$a.onSuccess(SourceFile:111) 
        at oif.N(SourceFile:30) 
        at v8f.a(SourceFile:3603) 
        at iif$a.onSuccess(SourceFile:84) 
        at tif$a.onSuccess(SourceFile:65) 
        at rif$a.run(SourceFile:81) 
        at e9f$b.run(SourceFile:124) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: j$.time.zone.ZoneRulesException: Unable to load TZDB time-zone rules
        at bze.d(SourceFile:105)
        at bze.e(SourceFile:85)
        at bze.c(SourceFile:50)
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(SourceFile:75)
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312)
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301)
        at j$.time.zone.ZoneRulesProvider$a.run(:154)
        at java.security.AccessController.doPrivileged(AccessController.java:43) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.j.R(:120) 
        at j$.time.ZoneId.N(:412) 
        at j$.time.ZoneId.of(:360) 
        at l84.f(SourceFile:313) 
        at l84.O(SourceFile:101) 
        at <omitted>(SourceFile:1102) 
        at j4e.lb(SourceFile:344) 
        at j4e.w6(SourceFile:332) 
        at j4e.x6(Unknown Source:0) 
        at m3e.accept(Unknown Source:4) 
        at zaf.onSuccess(SourceFile:62) 
        at iif$a$a.onSuccess(SourceFile:111) 
        at oif.N(SourceFile:30) 
        at v8f.a(SourceFile:3603) 
        at iif$a.onSuccess(SourceFile:84) 
        at tif$a.onSuccess(SourceFile:65) 
        at rif$a.run(SourceFile:81) 
        at e9f$b.run(SourceFile:124) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: j$.time.zone.ZoneOffsetTransitionRule.readExternal [interface java.io.DataInput]
        at xye.c(SourceFile:90)
        at yye.a(SourceFile:66)
        at xye.d(SourceFile:72)
        at xye.a(SourceFile:66)
        at bze.f(SourceFile:142)
        at bze.d(SourceFile:103)
        at bze.e(SourceFile:85) 
        at bze.c(SourceFile:50) 
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(SourceFile:75) 
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312) 
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301) 
        at j$.time.zone.ZoneRulesProvider$a.run(:154) 
        at java.security.AccessController.doPrivileged(AccessController.java:43) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.j.R(:120) 
        at j$.time.ZoneId.N(:412) 
        at j$.time.ZoneId.of(:360) 
        at l84.f(SourceFile:313) 
        at l84.O(SourceFile:101) 
        at <omitted>(SourceFile:1102) 
        at j4e.lb(SourceFile:344) 
        at j4e.w6(SourceFile:332) 
        at j4e.x6(Unknown Source:0) 
        at m3e.accept(Unknown Source:4) 
        at zaf.onSuccess(SourceFile:62) 
        at iif$a$a.onSuccess(SourceFile:111) 
        at oif.N(SourceFile:30) 
        at v8f.a(SourceFile:3603) 
        at iif$a.onSuccess(SourceFile:84) 
        at tif$a.onSuccess(SourceFile:65) 
        at rif$a.run(SourceFile:81) 
        at e9f$b.run(SourceFile:124) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.NoSuchMethodException: j$.time.zone.ZoneOffsetTransitionRule.readExternal [interface java.io.DataInput]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at xye.c(SourceFile:86)
        at yye.a(SourceFile:66) 
        at xye.d(SourceFile:72) 
        at xye.a(SourceFile:66) 
        at bze.f(SourceFile:142) 
        at bze.d(SourceFile:103) 
        at bze.e(SourceFile:85) 
        at bze.c(SourceFile:50) 
        at dev.zacsweers.ticktock.runtime.TickTockZoneRulesProvider.provideZoneIds(SourceFile:75) 
        at j$.time.zone.ZoneRulesProvider.registerProvider0(:312) 
        at j$.time.zone.ZoneRulesProvider.registerProvider(:301) 
        at j$.time.zone.ZoneRulesProvider$a.run(:154) 
        at java.security.AccessController.doPrivileged(AccessController.java:43) 
        at j$.time.zone.ZoneRulesProvider.<clinit>(:145) 
        at j$.time.zone.ZoneRulesProvider.getRules(:232) 
        at j$.time.j.R(:120) 
        at j$.time.ZoneId.N(:412) 
        at j$.time.ZoneId.of(:360) 
        at l84.f(SourceFile:313) 
        at l84.O(SourceFile:101)  
        at <omitted>(SourceFile:1102) 
        at j4e.lb(SourceFile:344) 
        at j4e.w6(SourceFile:332) 
        at j4e.x6(Unknown Source:0) 
        at m3e.accept(Unknown Source:4) 
        at zaf.onSuccess(SourceFile:62) 
        at iif$a$a.onSuccess(SourceFile:111) 
        at oif.N(SourceFile:30) 
        at v8f.a(SourceFile:3603) 
        at iif$a.onSuccess(SourceFile:84) 
        at tif$a.onSuccess(SourceFile:65) 
        at rif$a.run(SourceFile:81) 
        at e9f$b.run(SourceFile:124) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by kingsleyadio** [comment] 2021-03-04 10:37
So. I've been playing around with the L8 rules configuration, and after a few rounds of testing, this setting seem to work for me in the meantime:
```groovy
tasks.withType(L8DexDesugarLibTask) {
    keepRulesConfigurations.set(["-keep class j\$.time.zone.** { *; }"])
}
```

**Comment by ZacSweers** [comment] 2021-11-08 02:48
Nothing to do here, proguard configuration per app needs to be handled per app

**Closed by ZacSweers** 2021-11-08 02:48 UTC
